### ISSUE TITLE
Vertical orientation?

### ISSUE THREAD

**Issue by asongtoruin** [gyli/PyWaffle#12]
It would be interesting to be able to generate plots that were vertically orientated - i.e. rather than drawing the blocks column by column, they could be drawn row by row. I've got a basic working attempt at asongtoruin/pywaffle@e4d73b7 which adds the extra boolean kwarg `vertical` to do this, but I wasn't sure if this was functionality you think would be useful for the module.

For example, if we take the basic example from the examples folder:
`fig = plt.figure(FigureClass=Waffle, rows=5, columns=10, values=[48, 46, 3])`
this produces the following horizontal plot:
![basic_horiz](https://user-images.githubusercontent.com/20771863/65084907-96d64700-d9a4-11e9-8336-2c79cfe7fa05.png)

If we change this to
`fig = plt.figure(FigureClass=Waffle, rows=10, columns=5, values=[48, 46, 3], vertical=True)`
we instead get a vertically oriented plot:

![basic](https://user-images.githubusercontent.com/20771863/65084829-6393b800-d9a4-11e9-9659-d21344481fe5.png)

Thoughts?

**Comment by gyli** [comment]
Nice work. This is definitely something useful. Please feel free to submit a PR and we can test whether it works well with other parameters.
