### ISSUE TITLE
cant specify columns

### ISSUE THREAD

**Issue by rtphokie** [gyli/PyWaffle#14]
Each chart I create (python 3.7.4, PyWaffle 0.2.3) is coming out square regardless of what is passed in the columns parameter.  Its as if the columns parameter is being overwritten by what is passed to rows

        plt.figure(
            FigureClass=Waffle,
            rows=5,
            columns=10,
            values=[150, 75, 25],
            figsize=(16, 9)
        );
        plt.savefig('example.png')
![example](https://user-images.githubusercontent.com/551185/65697439-eb369200-e048-11e9-8757-e847995a67ac.png)

**Comment by gyli** [comment]
Interesting. Thanks for submitting the issue and I will take a look.
For now, could you please rollback the version to 0.2.1

**Comment by rtphokie** [comment]
The problem is not present in 0.2.1:
(same sample code as above)
![example](https://user-images.githubusercontent.com/551185/65719753-77aa7a00-e074-11e9-8381-8371dd3bfac7.png)

**Comment by gyli** [comment]
Fixed. Please upgrade to 0.2.4.
