### ISSUE TITLE
Font awesome license

### ISSUE THREAD

**Issue by toddrme2178** [gyli/PyWaffle#19]
I notice that files from the Font Awesome project are being used.  The project's license [requires attribution](https://fontawesome.com/license/free).  IANAL, and I am not affiliated with that project, but I think there probably needs to be a license file for these files, and this needs to be in the MANIFEST.in file (see #18) so it is included in sdists.

**Comment by gyli** [comment]
Nice catch.

Looks like having MANIFEST.in file is a better solution than specifying package_data in setup.py, since font files are missing in previous .tar.gz file.

I will merge the PR and exclude some docs and examples files, since that's only for ReadTheDocs.

**Comment by gyli** [comment]
https://github.com/gyli/PyWaffle/pull/18
