### ISSUE TITLE
Blocks of a single colour are not always contiguous

### ISSUE THREAD

**Issue by cpbl** [gyli/PyWaffle#20]
In this example output, the yellow block is split up, unnecessarily:

![zf7kX](https://user-images.githubusercontent.com/3696165/87829015-2316fc00-c84c-11ea-8204-03de5ef76cc5.png)
(from example at https://stackoverflow.com/questions/41400136/how-to-do-waffle-charts-in-python-square-piechart )

Shouldn't the rolling out of blocks go down one column, then up the next, then down the next, and so on, in order to  ensure that coloured regions remain contiguous?

**Comment by gyli** [comment]
This is the expected result, as the default drawing direction is from bottom left going up, then going right.
The starting location could be changed through parameter starting_location, and the direction could be changed through vertical. You can find more examples here https://pywaffle.readthedocs.io/en/latest/examples/block_shape_distance_location_and_direction.html

**Comment by cpbl** [comment]
Hi @gyli. Thanks for your package.

Those examples do not address the question of keeping colours contiguous.  You can consider this a feature request rather than a bug if you like, but I'm saying currently the output doesn't look good. It would look much better if the yellow blocks were contiguous, and I think your code could be fixed to ensure that.

**Comment by gyli** [comment]
I'm sorry that I din't get your point of keeping colors contiguous. If you take a look of the similar example in the README page, it is drawing from upper left to bottom right, while it does not avoid yellow blocks being separated, since there's just not enough blocks.
So in this case, what do you suggest to make yellow blocks being together? Making a new option to force each color starting from a new column maybe?

https://github.com/gyli/PyWaffle/raw/master/examples/readme/title_and_legend.svg

**Comment by cpbl** [comment]
That's not necessary. 
But it should draw down the first column, then up the next column, then down the next column, etc.
Then colours would never be broken up.

**Comment by gyli** [comment]
OK, that's also what I mean. I think we can do an option allowing this.

**Comment by gyli** [comment]
Just to confirm, is this what you thought? Every color starts from a new column so blocks with same color could be together. I am working on a new option to allow this.
![Figure_1](https://user-images.githubusercontent.com/2060045/87848371-904e7f80-c894-11ea-9b80-6bbea5b2130c.png)

**Comment by cpbl** [comment]
No.  That is painted top to bottom on every column.
My suggestion is to alternate directions on each column.

**Comment by cpbl** [comment]
The point is never to jump from the top to the bottom when you're painting. Lay down squares by snaking back and forth.

Look at my first example at the top of this Issue. 
The last two yellow squares should be at the top of their column, right next to the last yellow square painted in the previous column!

**Comment by gyli** [comment]
I see. That is a good point!

**Comment by gyli** [comment]
@cpbl The feature is added in the latest version 0.6.0. Use parameter block_arranging_style='snake' to enable it.

Thanks again for this great idea!

**Comment by cpbl** [comment]
Nice work, and thank you for this addition and for the project.
